/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comecajogo;

/**
 *
 * @author DANIEL_VE160
 */
public class DfrmInfo extends javax.swing.JDialog {

    /**
     * Creates new form DfrmInfo
     */
    public DfrmInfo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        lblCreditos = new javax.swing.JLabel();
        lblProgramacao = new javax.swing.JLabel();
        lblDaniell = new javax.swing.JLabel();
        lblPesquisa = new javax.swing.JLabel();
        lblGabriel = new javax.swing.JLabel();
        lblRuy = new javax.swing.JLabel();
        lblMaicon1 = new javax.swing.JLabel();
        lblWesley = new javax.swing.JLabel();
        lblDocumentacao = new javax.swing.JLabel();
        lblGabriel1 = new javax.swing.JLabel();
        lblRuy1 = new javax.swing.JLabel();
        lblMaicon2 = new javax.swing.JLabel();
        lblWesley1 = new javax.swing.JLabel();
        lblDesign = new javax.swing.JLabel();
        lblDaniel = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoInfo.png"))); // NOI18N
        btnVoltar.setBorder(null);
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.setFocusable(false);
        btnVoltar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoInfo2.png"))); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 170, 80));

        lblCreditos.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCreditos.setForeground(new java.awt.Color(255, 255, 255));
        lblCreditos.setText("CRÉDITOS");
        getContentPane().add(lblCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        lblProgramacao.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblProgramacao.setForeground(new java.awt.Color(255, 255, 255));
        lblProgramacao.setText("Programação");
        getContentPane().add(lblProgramacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lblDaniell.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDaniell.setForeground(new java.awt.Color(204, 204, 204));
        lblDaniell.setText("Daniel de Moura");
        getContentPane().add(lblDaniell, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, -1));

        lblPesquisa.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        lblPesquisa.setText("Pesquisa ");
        getContentPane().add(lblPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        lblGabriel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGabriel.setForeground(new java.awt.Color(204, 204, 204));
        lblGabriel.setText("Gabriel Franco");
        getContentPane().add(lblGabriel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 120, -1));

        lblRuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRuy.setForeground(new java.awt.Color(204, 204, 204));
        lblRuy.setText("Jose Ruy");
        getContentPane().add(lblRuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 120, -1));

        lblMaicon1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaicon1.setForeground(new java.awt.Color(204, 204, 204));
        lblMaicon1.setText("Maicon");
        getContentPane().add(lblMaicon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 120, -1));

        lblWesley.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWesley.setForeground(new java.awt.Color(204, 204, 204));
        lblWesley.setText("Wesley");
        getContentPane().add(lblWesley, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 120, -1));

        lblDocumentacao.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblDocumentacao.setForeground(new java.awt.Color(255, 255, 255));
        lblDocumentacao.setText("Documentação");
        getContentPane().add(lblDocumentacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        lblGabriel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGabriel1.setForeground(new java.awt.Color(204, 204, 204));
        lblGabriel1.setText("Gabriel Franco");
        getContentPane().add(lblGabriel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 120, -1));

        lblRuy1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRuy1.setForeground(new java.awt.Color(204, 204, 204));
        lblRuy1.setText("Jose Ruy");
        getContentPane().add(lblRuy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 120, -1));

        lblMaicon2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaicon2.setForeground(new java.awt.Color(204, 204, 204));
        lblMaicon2.setText("Maicon");
        getContentPane().add(lblMaicon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 120, -1));

        lblWesley1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWesley1.setForeground(new java.awt.Color(204, 204, 204));
        lblWesley1.setText("Wesley");
        getContentPane().add(lblWesley1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 120, -1));

        lblDesign.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblDesign.setForeground(new java.awt.Color(255, 255, 255));
        lblDesign.setText("Design");
        getContentPane().add(lblDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        lblDaniel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDaniel.setForeground(new java.awt.Color(204, 204, 204));
        lblDaniel.setText("Daniel de Moura");
        getContentPane().add(lblDaniel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, -1));

        lblFundo.setForeground(new java.awt.Color(204, 204, 204));
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblInfo.png"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 620, 470));

        setSize(new java.awt.Dimension(620, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblCreditos;
    private javax.swing.JLabel lblDaniel;
    private javax.swing.JLabel lblDaniell;
    private javax.swing.JLabel lblDesign;
    private javax.swing.JLabel lblDocumentacao;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblGabriel;
    private javax.swing.JLabel lblGabriel1;
    private javax.swing.JLabel lblMaicon1;
    private javax.swing.JLabel lblMaicon2;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblProgramacao;
    private javax.swing.JLabel lblRuy;
    private javax.swing.JLabel lblRuy1;
    private javax.swing.JLabel lblWesley;
    private javax.swing.JLabel lblWesley1;
    // End of variables declaration//GEN-END:variables
}
