/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comecajogo;

/**
 *
 * @author DANIEL_VE160
 */
public class frmCreditos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCreditos
     */
    public frmCreditos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPrincipal = new javax.swing.JDesktopPane();
        tnVoltar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblCredito1 = new javax.swing.JLabel();
        lblCredito = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setBorder(null);

        dpPrincipal.setPreferredSize(new java.awt.Dimension(1380, 850));

        tnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnVoltar Credito.png"))); // NOI18N
        tnVoltar.setBorder(null);
        tnVoltar.setContentAreaFilled(false);
        tnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tnVoltar.setFocusable(false);
        tnVoltar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnVoltar Credito3.png"))); // NOI18N
        tnVoltar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnVoltar Credito2.png"))); // NOI18N
        tnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnVoltarActionPerformed(evt);
            }
        });
        dpPrincipal.add(tnVoltar);
        tnVoltar.setBounds(570, 530, 200, 90);

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblTituloCredito.png"))); // NOI18N
        dpPrincipal.add(lblTitulo);
        lblTitulo.setBounds(480, 90, 380, 90);

        jScrollPane1.setBackground(new java.awt.Color(0, 153, 51));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCredito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblCredito.png"))); // NOI18N
        jScrollPane1.setViewportView(lblCredito1);

        dpPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(390, 180, 570, 350);

        lblCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblCreditoFundoVerde.png"))); // NOI18N
        dpPrincipal.add(lblCredito);
        lblCredito.setBounds(300, 110, 760, 500);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblCreditoeSair.jpg"))); // NOI18N
        lblFundo.setToolTipText("");
        dpPrincipal.add(lblFundo);
        lblFundo.setBounds(0, -7, 1380, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1365, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        setBounds(0, -27, 1365, 734);
    }// </editor-fold>//GEN-END:initComponents

    private void tnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnVoltarActionPerformed
        // BOTÃO VOLTAR
        dispose();
    }//GEN-LAST:event_tnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCredito;
    private javax.swing.JLabel lblCredito1;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JButton tnVoltar;
    // End of variables declaration//GEN-END:variables
}
