/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comecajogo;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Toolkit;
import java.net.URL;
import telalogin.frmLogin;

/**
 *
 * @author DANIEL_VE160
 */
public class frmJogar extends javax.swing.JFrame {

    /**
     * Creates new form frmJogar
     */
    
    public frmJogar() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);
        //setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);//desabilita o botão fechar
        setIcone(); 
    }
    
    //METODO PARA TOCAR UM EFEITO DE BOTÃO
    public static void play2(String nomeDoAudio){
        new Thread(){
            public void run(){
                URL url = frmJogar.class.getResource(nomeDoAudio+".wav");
                AudioClip audio = Applet.newAudioClip(url);
                audio.play();               
            }
        }.start();        
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPrincipal = new javax.swing.JDesktopPane();
        btnInfo = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnAlfabeto = new javax.swing.JButton();
        btnQuiz = new javax.swing.JButton();
        btnConfigura = new javax.swing.JButton();
        lblCabecalho = new javax.swing.JLabel();
        lblObs = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SOSLibras");
        setResizable(false);

        dpPrincipal.setPreferredSize(new java.awt.Dimension(1380, 850));

        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnCredito.png"))); // NOI18N
        btnInfo.setBorder(null);
        btnInfo.setBorderPainted(false);
        btnInfo.setContentAreaFilled(false);
        btnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInfo.setFocusPainted(false);
        btnInfo.setFocusable(false);
        btnInfo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnCredito.png"))); // NOI18N
        btnInfo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnCredito2.png"))); // NOI18N
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        dpPrincipal.add(btnInfo);
        btnInfo.setBounds(110, 10, 60, 70);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnSair_1.png"))); // NOI18N
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setFocusPainted(false);
        btnSair.setFocusable(false);
        btnSair.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnSair_1.png"))); // NOI18N
        btnSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnSair2_1.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        dpPrincipal.add(btnSair);
        btnSair.setBounds(1160, 10, 60, 65);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tituloLibras_1.png"))); // NOI18N
        dpPrincipal.add(lblTitulo);
        lblTitulo.setBounds(460, 0, 390, 90);

        btnAlfabeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnJogoAlfabeto1.png"))); // NOI18N
        btnAlfabeto.setBorder(null);
        btnAlfabeto.setBorderPainted(false);
        btnAlfabeto.setContentAreaFilled(false);
        btnAlfabeto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlfabeto.setFocusable(false);
        btnAlfabeto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnJogoAlfabeto2.png"))); // NOI18N
        btnAlfabeto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnJogoAlfabeto0.png"))); // NOI18N
        btnAlfabeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlfabetoActionPerformed(evt);
            }
        });
        dpPrincipal.add(btnAlfabeto);
        btnAlfabeto.setBounds(780, 190, 280, 270);

        btnQuiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnJogoQuiz1.png"))); // NOI18N
        btnQuiz.setBorder(null);
        btnQuiz.setBorderPainted(false);
        btnQuiz.setContentAreaFilled(false);
        btnQuiz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuiz.setFocusable(false);
        btnQuiz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnJogoQuiz2.png"))); // NOI18N
        btnQuiz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnJogoQuiz0.png"))); // NOI18N
        btnQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuizActionPerformed(evt);
            }
        });
        dpPrincipal.add(btnQuiz);
        btnQuiz.setBounds(310, 190, 280, 270);

        btnConfigura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblLogin.png"))); // NOI18N
        btnConfigura.setBorderPainted(false);
        btnConfigura.setContentAreaFilled(false);
        btnConfigura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfigura.setFocusPainted(false);
        btnConfigura.setFocusable(false);
        btnConfigura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfigura.setIconTextGap(3);
        btnConfigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguraActionPerformed(evt);
            }
        });
        dpPrincipal.add(btnConfigura);
        btnConfigura.setBounds(20, 10, 60, 70);

        lblCabecalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblCabecalho.png"))); // NOI18N
        lblCabecalho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        dpPrincipal.add(lblCabecalho);
        lblCabecalho.setBounds(-20, -10, 1420, 99);

        lblObs.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblObs.setForeground(new java.awt.Color(255, 255, 255));
        lblObs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblAviso.png"))); // NOI18N
        lblObs.setPreferredSize(new java.awt.Dimension(750, 80));
        dpPrincipal.add(lblObs);
        lblObs.setBounds(20, 570, 1210, 80);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/01desktopFundo.png"))); // NOI18N
        lblFundo.setToolTipText("");
        dpPrincipal.add(lblFundo);
        lblFundo.setBounds(0, 0, 1380, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1315, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1331, 735));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
       // FRMCREDITOS
       frmCreditos creditos = new frmCreditos();
       dpPrincipal.add(creditos);
       creditos.setVisible(true);
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       // new frmSair(null, rootPaneCheckingEnabled).setVisible(true);
       frmSair sair = new frmSair();
       dpPrincipal.add(sair);
       sair.setVisible(true);       
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConfiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguraActionPerformed
       frmLogin login = new frmLogin();
       login.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnConfiguraActionPerformed

    private void btnQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuizActionPerformed
        // BOTÃO JOGAR ALFABETO DE LIBRAS
        frmQuizTela fpto = new frmQuizTela();
        dpPrincipal.add(fpto);
        fpto.setVisible(true);
    }//GEN-LAST:event_btnQuizActionPerformed

    private void btnAlfabetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlfabetoActionPerformed
        // BOTÃO JOGAR ALFABETO DE LIBRAS
        frmAlfabetoLibras libras = new frmAlfabetoLibras();
        dpPrincipal.add(libras);
        libras.setVisible(true);        
    }//GEN-LAST:event_btnAlfabetoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlfabeto;
    private javax.swing.JButton btnConfigura;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnQuiz;
    private javax.swing.JButton btnSair;
    private javax.swing.JDesktopPane dpPrincipal;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    public void setIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icone1.png")));
    }

}

