/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comecajogo;

/**
 *
 * @author DANIEL_VE160
 */
public class frmSair extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCreditos
     */
    public frmSair() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPrincipal = new javax.swing.JDesktopPane();
        btnSim = new javax.swing.JButton();
        btnNao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblCredito = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setBorder(null);

        dpPrincipal.setPreferredSize(new java.awt.Dimension(1380, 850));

        btnSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoSIM2.png"))); // NOI18N
        btnSim.setBorder(null);
        btnSim.setContentAreaFilled(false);
        btnSim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSim.setFocusable(false);
        btnSim.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoSIM1.png"))); // NOI18N
        btnSim.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoSIM1.png"))); // NOI18N
        btnSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimActionPerformed(evt);
            }
        });
        dpPrincipal.add(btnSim);
        btnSim.setBounds(420, 470, 170, 70);

        btnNao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoNaoLibra.png"))); // NOI18N
        btnNao.setBorder(null);
        btnNao.setContentAreaFilled(false);
        btnNao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNao.setFocusable(false);
        btnNao.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoNao1.png"))); // NOI18N
        btnNao.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaoNao1.png"))); // NOI18N
        btnNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaoActionPerformed(evt);
            }
        });
        dpPrincipal.add(btnNao);
        btnNao.setBounds(790, 470, 170, 70);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Você Deseja Realmente Sair");
        dpPrincipal.add(jLabel1);
        jLabel1.setBounds(430, 300, 520, 50);

        lblCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblSair2.png"))); // NOI18N
        dpPrincipal.add(lblCredito);
        lblCredito.setBounds(370, 110, 620, 460);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblCreditoeSair.jpg"))); // NOI18N
        lblFundo.setToolTipText("");
        dpPrincipal.add(lblFundo);
        lblFundo.setBounds(0, -7, 1380, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1365, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        setBounds(0, -27, 1365, 734);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaoActionPerformed
        // BOTÃO VOLTAR
        dispose();
    }//GEN-LAST:event_btnNaoActionPerformed

    private void btnSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimActionPerformed
        // BOTÃO SAIR
        System.exit(0);
    }//GEN-LAST:event_btnSimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNao;
    private javax.swing.JButton btnSim;
    private javax.swing.JDesktopPane dpPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCredito;
    private javax.swing.JLabel lblFundo;
    // End of variables declaration//GEN-END:variables
}
