/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telalogin;

import dao.UsuarioDAO;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import model.Usuario;

/**
 *
 * @author DANIEL_VE160
 */
public class frmCadastrar extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmCadastrar() {
        initComponents();
        txtNome.setCaretColor(java.awt.Color.white);// Muadr A cor do cusor piscando para branco
        pwdSenha.setCaretColor(java.awt.Color.white);
        pwdConfiSenha.setCaretColor(java.awt.Color.white);
        // pwdSenha.setCaretColor(pwdSenha.getBackground());//desabilitar o cursor
        // piscando
        JOptionPane.showMessageDialog(null, "Nos campos senha digite no maxímo 9 numeros");
        pwdSenha.setDocument(new LimitadorTxt(9, "[aA-zZ]"));
        pwdConfiSenha.setDocument(new LimitadorTxt(9, "[aA-zZ]"));
        txtNome.setDocument(new LimitadorTxt(23, "[0-9]"));
        setIcone();
    }

    // Metodo Responsavel por bloquear no campo de texto os tipos de valores que vai
    // ser aceito
    // e limitar da quantidade de digitos que vai ser digitados
    class LimitadorTxt extends PlainDocument {
        int tan = 0;
        String regex = "";

        public LimitadorTxt(int a, String r) {

            this.tan = a;
            this.regex = r;
        }

        @Override
        public void insertString(int offs, String str, AttributeSet a) throws BadLocationException {
            int tamanho = (this.getLength() + str.length());
            if (tamanho <= tan) {
                super.insertString(offs, str.replaceAll(regex, ""), a);
            } else {
                super.insertString(offs, str.replaceAll("[aA0-zZ9]", ""), a);
            }
        }
    }

    public void cadastrar() {
        Usuario us = new Usuario();
        UsuarioDAO d = new UsuarioDAO();
        // Validação dos Campos Nome Senha e ConfiSenha
        if (txtNome.getText().isEmpty() || (pwdSenha.getText().isEmpty()) || (pwdConfiSenha.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Preencha Todos os Campos");
        } else {
            try {
                us.setNome(txtNome.getText());
                // Validação dos Campos Senha se Elas Comferem Ex: Senha:123 / ConfiSenha:123
                if (pwdSenha.getText() == null ? pwdConfiSenha.getText() == null
                        : pwdSenha.getText().equals(pwdConfiSenha.getText())) {
                    us.setSenha(Integer.parseInt(pwdSenha.getText()));
                    us.setConfiSenha(Integer.parseInt(pwdConfiSenha.getText()));
                    d.create(us);
                    // JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso");
                    new frmLogin().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "as senhas digitadas não conferem");
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,
                        "ATENÇÃO ouve algum erro na sua conexão com o Banco de Dados: " + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        pwdSenha = new javax.swing.JPasswordField();
        pwdConfiSenha = new javax.swing.JPasswordField();
        btnCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblConfSenha = new javax.swing.JLabel();
        btnSair1 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(370, 510));
        getContentPane().setLayout(null);

        txtNome.setBackground(new java.awt.Color(0, 51, 153));
        txtNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtNome);
        txtNome.setBounds(140, 290, 160, 30);

        pwdSenha.setBackground(new java.awt.Color(0, 51, 153));
        pwdSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pwdSenha.setForeground(new java.awt.Color(255, 255, 255));
        pwdSenha.setToolTipText("");
        getContentPane().add(pwdSenha);
        pwdSenha.setBounds(140, 330, 160, 30);

        pwdConfiSenha.setBackground(new java.awt.Color(0, 51, 153));
        pwdConfiSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pwdConfiSenha.setForeground(new java.awt.Color(255, 255, 255));
        pwdConfiSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdConfiSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(pwdConfiSenha);
        pwdConfiSenha.setBounds(140, 370, 160, 30);

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnCadastrar.png"))); // NOI18N
        btnCadastrar.setBorder(null);
        btnCadastrar.setBorderPainted(false);
        btnCadastrar.setContentAreaFilled(false);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setFocusable(false);
        btnCadastrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnCadastrar2.png"))); // NOI18N
        btnCadastrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnCadastrar2.png"))); // NOI18N
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(150, 430, 180, 70);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 290, 50, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("    Senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 330, 70, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/loginAvatar.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 40, 220, 240);

        lblConfSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConfSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblConfSenha.setText(" Confirmar Senha:");
        getContentPane().add(lblConfSenha);
        lblConfSenha.setBounds(0, 370, 130, 30);

        btnSair1.setBackground(new java.awt.Color(255, 255, 255));
        btnSair1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnVoltarL.png"))); // NOI18N
        btnSair1.setBorder(null);
        btnSair1.setBorderPainted(false);
        btnSair1.setContentAreaFilled(false);
        btnSair1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair1.setFocusable(false);
        btnSair1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnVoltarL2.png"))); // NOI18N
        btnSair1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnVoltarL2.png"))); // NOI18N
        btnSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair1);
        btnSair1.setBounds(0, 0, 180, 50);

        btnSair.setBackground(new java.awt.Color(255, 255, 255));
        btnSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnSair.png"))); // NOI18N
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setFocusable(false);
        btnSair.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnSair2.png"))); // NOI18N
        btnSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnSair2.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(230, 0, 140, 50);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar.png"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 370, 530);

        setSize(new java.awt.Dimension(367, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCadastrarActionPerformed
        cadastrar();

    }// GEN-LAST:event_btnCadastrarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }// GEN-LAST:event_btnSairActionPerformed

    private void btnSair1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSair1ActionPerformed
        // btnVOLTAR
        new frmLogin().setVisible(true);
        dispose();
    }// GEN-LAST:event_btnSair1ActionPerformed

    private void pwdConfiSenhaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pwdConfiSenhaActionPerformed
        // TODO add your handling code here:
        cadastrar();
    }// GEN-LAST:event_pwdConfiSenhaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSair1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblConfSenha;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JPasswordField pwdConfiSenha;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

    private void setIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icone1.png")));
    }
}
