/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medio;



import comecajogo.frmJogar;
import comecajogo.frmMsgCerto;
import facil.frmFimdejogo;
import javax.swing.JOptionPane;


/**
 *
 * @author DANIEL_VE160
 */
public class frmMedio3 extends javax.swing.JInternalFrame {


    /**
     * Creates new form frmQuizTela
     */
    private  int chances = 2;
    private boolean passou = false;
    private boolean selecao = false;
    
    
    //METODO QUE CONTA QUANTAS CHANCES VOCÊ TEM
    //QUE RECEBE COMO PARAMETRO UM NUMERO
    //E SETA O VALOR DA VARIAL CHANCES
    private void contador(int n){
        chances = chances-n;
    }
   
    //METODO QUE RECEBER UM VALOR DO FRM ANTERIO
    //E SETA O VALOR DA VARIAL CHANCES
    public void recebeChance3(int r){
        chances = r;
    }
    public frmMedio3() {
        initComponents();
        
    }
    
    //Metodo Responsavel para mudar a imagem e texto da label 
    //quando a resposta que é o botão selecionado estiver errado 
    //a label se chama lblVisualiza 
    private void visuaImage(){
        lblTemChance3.setText(""+chances);
        lblVisualiza.setIcon(null);
        lblVisualiza.setText("Resposta Errada");
        mensagemTela();
        //JOptionPane.showMessageDialog(null, "Resposta errada você tem "+chances+" chances");
        lblVisualiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/questM3p.jpg")));
        lblVisualiza.setText(""); 
    }
    frmFimdejogo fim = new frmFimdejogo();
    //Mostra a mensagem na tela se Acertou ou Errou a Alternativa selecionada
    public void mensagemTela(){
        //JOptionPane.showMessageDialog(null, "Resposta errada você tem "+chances+" chances");
        // Instanciando o formulario frmMsgCerto e setando a imgem para errado e mostrando quantas chances tem
        //quando for a respota errada mostre o formulario com a imagem e numero de chances        
        frmMsgCerto errado = new frmMsgCerto(null, rootPaneCheckingEnabled);
        errado.lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/msgErrado.jpg")));
        switch(chances){
            case 1:
                errado.lblChance3.setVisible(false);
                errado.lblChance2.setVisible(false);
                errado.lblChance1.setText("1");
                frmJogar.play2("/audio/errou");
                break; 
            case 0:
                errado.lblChance1.setVisible(false);
                errado.lblChance2.setVisible(false);
                errado.lblChance3.setText("0"); 
                frmJogar.play2("/audio/errou");
                fim.lblPontos.setText("20");
                fim.lblQuestao.setText("QUESTÃO 3");  
                fim.lblTemChance.setText("0");
                fim.lblTotChance.setText("2");                 
                break;                
        }// fim do switch
        errado.setVisible(true);//Mostrando o formulario frmMsgCerto        
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnOk1 = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jcpPergunta = new javax.swing.JScrollPane();
        jtxtpC1 = new javax.swing.JTextPane();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        txtD = new javax.swing.JTextField();
        txtE = new javax.swing.JTextField();
        txtConfiRes = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblVisualiza = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPotuacao = new javax.swing.JLabel();
        lblPontos = new javax.swing.JLabel();
        lblChances = new javax.swing.JLabel();
        lblTemChance3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotChance = new javax.swing.JLabel();
        lblCabecalho = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(null);

        btnOk1.setFont(new java.awt.Font("Poetsen One", 0, 24)); // NOI18N
        btnOk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnL3.png"))); // NOI18N
        btnOk1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnOk1.setContentAreaFilled(false);
        btnOk1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOk1.setFocusable(false);
        btnOk1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btn3.png"))); // NOI18N
        jDesktopPane1.add(btnOk1);
        btnOk1.setBounds(20, 20, 70, 60);

        btnA.setFont(new java.awt.Font("Poetsen One", 0, 24)); // NOI18N
        btnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnA.png"))); // NOI18N
        btnA.setBorder(null);
        btnA.setContentAreaFilled(false);
        btnA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnA.setFocusable(false);
        btnA.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnA2.png"))); // NOI18N
        btnA.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnA2.png"))); // NOI18N
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnA);
        btnA.setBounds(680, 20, 70, 60);

        btnB.setFont(new java.awt.Font("Poetsen One", 0, 24)); // NOI18N
        btnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnB.png"))); // NOI18N
        btnB.setBorder(null);
        btnB.setContentAreaFilled(false);
        btnB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnB.setFocusable(false);
        btnB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnB2.png"))); // NOI18N
        btnB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnB2.png"))); // NOI18N
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnB);
        btnB.setBounds(680, 100, 70, 60);

        btnC.setFont(new java.awt.Font("Poetsen One", 0, 24)); // NOI18N
        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnC.png"))); // NOI18N
        btnC.setBorder(null);
        btnC.setContentAreaFilled(false);
        btnC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC.setFocusable(false);
        btnC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnC2.png"))); // NOI18N
        btnC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnC2.png"))); // NOI18N
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnC);
        btnC.setBounds(680, 170, 70, 60);

        btnD.setFont(new java.awt.Font("Poetsen One", 0, 24)); // NOI18N
        btnD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnD.png"))); // NOI18N
        btnD.setBorder(null);
        btnD.setContentAreaFilled(false);
        btnD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnD.setFocusable(false);
        btnD.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnD2.png"))); // NOI18N
        btnD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnD2.png"))); // NOI18N
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnD);
        btnD.setBounds(680, 240, 70, 60);

        btnE.setFont(new java.awt.Font("Poetsen One", 0, 24)); // NOI18N
        btnE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnE.png"))); // NOI18N
        btnE.setBorder(null);
        btnE.setContentAreaFilled(false);
        btnE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnE.setFocusable(false);
        btnE.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnE2.png"))); // NOI18N
        btnE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnE2.png"))); // NOI18N
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnE);
        btnE.setBounds(680, 310, 70, 60);

        btnOk.setFont(new java.awt.Font("Poetsen One", 0, 24)); // NOI18N
        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnOK.png"))); // NOI18N
        btnOk.setBorder(null);
        btnOk.setContentAreaFilled(false);
        btnOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOk.setFocusable(false);
        btnOk.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnOK2.png"))); // NOI18N
        btnOk.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnOK2.png"))); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnOk);
        btnOk.setBounds(680, 380, 70, 60);

        jcpPergunta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jcpPergunta.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jcpPergunta.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        jtxtpC1.setEditable(false);
        jtxtpC1.setBackground(new java.awt.Color(0, 102, 102));
        jtxtpC1.setBorder(null);
        jtxtpC1.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jtxtpC1.setForeground(new java.awt.Color(255, 255, 255));
        jtxtpC1.setText("Quando alguém desmaia, o que é mais perigoso em causar engasgamento?");
        jtxtpC1.setFocusable(false);
        jcpPergunta.setViewportView(jtxtpC1);

        jDesktopPane1.add(jcpPergunta);
        jcpPergunta.setBounds(90, 20, 570, 60);

        txtA.setEditable(false);
        txtA.setBackground(new java.awt.Color(0, 102, 102));
        txtA.setFont(new java.awt.Font("SansSerif", 0, 21)); // NOI18N
        txtA.setForeground(new java.awt.Color(255, 255, 255));
        txtA.setText(" Quando desmaiada a pessoa se esquece de puxar o ar");
        txtA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtA.setFocusable(false);
        jDesktopPane1.add(txtA);
        txtA.setBounds(750, 20, 530, 60);

        txtB.setEditable(false);
        txtB.setBackground(new java.awt.Color(0, 102, 102));
        txtB.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtB.setForeground(new java.awt.Color(255, 255, 255));
        txtB.setText(" Sangue do nariz que entope a garganta");
        txtB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtB.setFocusable(false);
        jDesktopPane1.add(txtB);
        txtB.setBounds(750, 170, 530, 60);

        txtC.setEditable(false);
        txtC.setBackground(new java.awt.Color(0, 102, 102));
        txtC.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtC.setForeground(new java.awt.Color(255, 255, 255));
        txtC.setText(" Dentes quebrados que são engolidos");
        txtC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtC.setFocusable(false);
        jDesktopPane1.add(txtC);
        txtC.setBounds(750, 100, 530, 60);

        txtD.setEditable(false);
        txtD.setBackground(new java.awt.Color(0, 102, 102));
        txtD.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtD.setForeground(new java.awt.Color(255, 255, 255));
        txtD.setText(" A própria língua ao relaxar");
        txtD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtD.setFocusable(false);
        jDesktopPane1.add(txtD);
        txtD.setBounds(750, 240, 530, 60);

        txtE.setEditable(false);
        txtE.setBackground(new java.awt.Color(0, 102, 102));
        txtE.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtE.setForeground(new java.awt.Color(255, 255, 255));
        txtE.setText(" Nenhuma das opções");
        txtE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtE.setFocusable(false);
        jDesktopPane1.add(txtE);
        txtE.setBounds(750, 310, 530, 60);

        txtConfiRes.setEditable(false);
        txtConfiRes.setBackground(new java.awt.Color(0, 102, 102));
        txtConfiRes.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtConfiRes.setForeground(new java.awt.Color(255, 255, 255));
        txtConfiRes.setText(" CONFIRMAR A RESPOSTA");
        txtConfiRes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtConfiRes.setFocusable(false);
        jDesktopPane1.add(txtConfiRes);
        txtConfiRes.setBounds(750, 380, 310, 60);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblVisualiza.setBackground(new java.awt.Color(255, 255, 255));
        lblVisualiza.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblVisualiza.setForeground(new java.awt.Color(255, 255, 255));
        lblVisualiza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVisualiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/questM3p.jpg"))); // NOI18N
        lblVisualiza.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblVisualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(574, 574, 574))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblVisualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(20, 90, 640, 350);

        jLabel3.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QUESTÃO 3");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(40, 550, 280, 60);

        lblPotuacao.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        lblPotuacao.setForeground(new java.awt.Color(255, 255, 255));
        lblPotuacao.setText("Pontuação:");
        jDesktopPane1.add(lblPotuacao);
        lblPotuacao.setBounds(520, 550, 210, 60);

        lblPontos.setFont(new java.awt.Font("Poetsen One", 0, 36)); // NOI18N
        lblPontos.setForeground(new java.awt.Color(255, 255, 255));
        lblPontos.setText("20");
        jDesktopPane1.add(lblPontos);
        lblPontos.setBounds(710, 560, 100, 40);

        lblChances.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        lblChances.setForeground(new java.awt.Color(0, 204, 102));
        lblChances.setText("Chances:");
        jDesktopPane1.add(lblChances);
        lblChances.setBounds(1010, 550, 180, 60);

        lblTemChance3.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        lblTemChance3.setForeground(new java.awt.Color(204, 0, 51));
        lblTemChance3.setText("2");
        jDesktopPane1.add(lblTemChance3);
        lblTemChance3.setBounds(1170, 550, 50, 60);

        jLabel2.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 102));
        jLabel2.setText("/");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(1200, 550, 40, 60);

        lblTotChance.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        lblTotChance.setForeground(new java.awt.Color(0, 204, 102));
        lblTotChance.setText("2");
        jDesktopPane1.add(lblTotChance);
        lblTotChance.setBounds(1220, 550, 50, 60);

        lblCabecalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblCabecalho.png"))); // NOI18N
        lblCabecalho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jDesktopPane1.add(lblCabecalho);
        lblCabecalho.setBounds(-10, 530, 1400, 100);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/01desktopFundo.png"))); // NOI18N
        lblFundo.setText(" Resposta");
        lblFundo.setToolTipText("");
        lblFundo.setFocusable(false);
        jDesktopPane1.add(lblFundo);
        lblFundo.setBounds(0, 0, 1380, 700);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 1380, 700);

        setBounds(0, -27, 1378, 660);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // BOTAO A
        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO B
        btnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnB.png")));
        btnB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnB2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO C
        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnC.png")));
        btnC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnC2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO D
        btnD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnD.png")));
        btnD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnD2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO E
        btnE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnE.png")));
        btnE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnE2.png")));

        //MUDANDO A IMAGEM DO BOTÃO A PARA A IMAGEM SELECAO
        btnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnA2.png")));
        
        passou = false;
        selecao = true;
    }//GEN-LAST:event_btnAActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // BOTÃO C
        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO A
        btnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnA.png")));
        btnA.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnA2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO B
        btnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnB.png")));
        btnB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnB2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO D
        btnD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnD.png")));
        btnD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnD2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO E
        btnE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnE.png")));
        btnE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnE2.png")));

        //MUDANDO A IMAGEM DO BOTÃO C PARA A IMAGEM SELECAO
        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnC2.png")));
        
        passou = false;
        selecao = true;
    }//GEN-LAST:event_btnCActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // BOTÃO OK
        if(selecao == true){
            if (passou == true) {
                lblVisualiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/questM3r.jpg")));
                lblPontos.setText("30");                     
                frmJogar.play2("/audio/acertou");
                //JOptionPane.showMessageDialog(null, "Resposta Correta Passe Para Próxima Questão Você Tem "+chances+" chances");
                frmMsgCerto certo = new frmMsgCerto(null, rootPaneCheckingEnabled);
                certo.lblChance3.setText(""+chances);
                certo.setVisible(true);
                
                frmMedio4 m4 = new frmMedio4();
                jDesktopPane1.add(m4);//ABRINDO O PROXIMO FRM
                m4.setVisible(true);//DEIXANDO O FRM VISIVEL
                
                m4.recebeChance4(chances);//PASSANDO PARA A VARIAL CHANCES DO PROXIMO FRM QUANTAS CHANCES AINDA TEM
                m4.lblTemChance4.setText(""+chances);//PASSANDO PARA A LBL DO PROXIMO FRM O TEXTO DE CHANCES                 
            }else{
                contador(1);
                switch(chances){
                    case 0: 
                        visuaImage();
                        jDesktopPane1.add(fim);
                        fim.setVisible(true);
                        break;
                    default:
                        visuaImage();
                        break;
                }//fim switch
            }
        }else{
          JOptionPane.showMessageDialog(null, "Por favor selecione um questão"); 
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        // BOTÃO B
        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO A
        btnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnA.png")));
        btnA.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnA2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO C
        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnC.png")));
        btnC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnC2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO D
        btnD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnD.png")));
        btnD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnD2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO E
        btnE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnE.png")));
        btnE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnE2.png")));

        //MUDANDO A IMAGEM DO BOTÃO B PARA A IMAGEM SELECAO
        btnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnB2.png")));
        
        passou = false;
        selecao = true;
    }//GEN-LAST:event_btnBActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // BOTÃO E
        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO A
        btnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnA.png")));
        btnA.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnA2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO B
        btnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnB.png")));
        btnB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnB2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO C
        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnC.png")));
        btnC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnC2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO D
        btnD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnD.png")));
        btnD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnD2.png")));

        //MUDANDO A IMAGEM DO BOTÃO E PARA A IMAGEM SELECAO
        btnE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnE2.png")));
        
        passou = false;
        selecao = true;
    }//GEN-LAST:event_btnEActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        // BOTÃO D
        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO A
        btnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnA.png")));
        btnA.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnA2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO B
        btnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnB.png")));
        btnB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnB2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO C
        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnC.png")));
        btnC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnC2.png")));

        //VOLTANDO PARA A IMAGEM INICIAL DO BOTÃO E
        btnE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnE.png")));
        btnE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnE2.png")));

        //MUDANDO A IMAGEM DO BOTÃO D PARA A IMAGEM SELECAO
        btnD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnD2.png")));
        
        passou = true;
        selecao = true;
    }//GEN-LAST:event_btnDActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnOk1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jcpPergunta;
    private javax.swing.JTextPane jtxtpC1;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblChances;
    private javax.swing.JLabel lblFundo;
    public javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lblPotuacao;
    public javax.swing.JLabel lblTemChance3;
    private javax.swing.JLabel lblTotChance;
    private javax.swing.JLabel lblVisualiza;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtConfiRes;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtE;
    // End of variables declaration//GEN-END:variables

}
