/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facil;

import javax.swing.JOptionPane;


/**
 *
 * @author DANIEL_VE160
 */
public class frmFimdejogo extends javax.swing.JInternalFrame {

    frmFacil facil = new frmFacil();
    /**
     * Creates new form frmQuizTela
     */
    private  int chances = 0;
    private boolean selecao = false;
    private boolean passou = false;
    
    public frmFimdejogo() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTemChance = new javax.swing.JLabel();
        lblPotuacao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotChance = new javax.swing.JLabel();
        lblChances = new javax.swing.JLabel();
        lblPontos = new javax.swing.JLabel();
        lblQuestao = new javax.swing.JLabel();
        lblCabecalho = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setBorder(null);
        getContentPane().setLayout(null);

        lblTemChance.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        lblTemChance.setForeground(new java.awt.Color(204, 0, 51));
        lblTemChance.setText("0");
        getContentPane().add(lblTemChance);
        lblTemChance.setBounds(1170, 550, 50, 60);

        lblPotuacao.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        lblPotuacao.setForeground(new java.awt.Color(255, 255, 255));
        lblPotuacao.setText("Pontuação:");
        getContentPane().add(lblPotuacao);
        lblPotuacao.setBounds(520, 550, 210, 60);

        jLabel2.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 102));
        jLabel2.setText("/");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1200, 550, 40, 60);

        lblTotChance.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        lblTotChance.setForeground(new java.awt.Color(0, 204, 102));
        lblTotChance.setText("3");
        getContentPane().add(lblTotChance);
        lblTotChance.setBounds(1220, 550, 50, 60);

        lblChances.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        lblChances.setForeground(new java.awt.Color(0, 204, 102));
        lblChances.setText("Chances:");
        getContentPane().add(lblChances);
        lblChances.setBounds(1010, 550, 180, 60);

        lblPontos.setFont(new java.awt.Font("Poetsen One", 0, 36)); // NOI18N
        lblPontos.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblPontos);
        lblPontos.setBounds(710, 560, 100, 40);

        lblQuestao.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        lblQuestao.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestao.setText("QUESTÃO 1");
        getContentPane().add(lblQuestao);
        lblQuestao.setBounds(40, 550, 280, 60);

        lblCabecalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblCabecalho.png"))); // NOI18N
        lblCabecalho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(lblCabecalho);
        lblCabecalho.setBounds(-10, 530, 1394, 100);

        lblFundo.setBackground(new java.awt.Color(153, 0, 0));
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblFimdoJogo_1.jpg"))); // NOI18N
        lblFundo.setText(" Resposta");
        lblFundo.setToolTipText("");
        lblFundo.setFocusable(false);
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1380, 700);
        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 1380, 700);

        setBounds(0, -27, 1378, 660);
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblChances;
    private javax.swing.JLabel lblFundo;
    public javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lblPotuacao;
    public javax.swing.JLabel lblQuestao;
    public javax.swing.JLabel lblTemChance;
    public javax.swing.JLabel lblTotChance;
    // End of variables declaration//GEN-END:variables

}
