/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facil;

import comecajogo.frmJogar;
import java.applet.Applet;
import java.applet.AudioClip;
import java.net.URL;
/**
 *
 * @author DANIEL_VE160
 */
public class frmGanhou extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmGanhou
     */
    public frmGanhou() {
        initComponents();
    }
    boolean para = false;
    
    public void setPara(boolean para){
        this.para = para;
    }
    
    AudioClip audio;
    //METODO PARA TOCAR UM EFEITO DE BOTÃO
    public void play(String nomeDoAudio){
        new Thread(){
            public void run(){
                URL url = frmJogar.class.getResource(nomeDoAudio+".wav");
                audio = Applet.newAudioClip(url);
                audio.play();               
            }
        }.start();        
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPotuacao = new javax.swing.JLabel();
        lblChances = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPontos = new javax.swing.JLabel();
        lblTemChance11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotChance11 = new javax.swing.JLabel();
        lblCabecalho = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lblPotuacao.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        lblPotuacao.setForeground(new java.awt.Color(255, 255, 255));
        lblPotuacao.setText("Pontuação:");
        getContentPane().add(lblPotuacao);
        lblPotuacao.setBounds(520, 550, 210, 60);

        lblChances.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        lblChances.setForeground(new java.awt.Color(0, 204, 102));
        lblChances.setText("Chances:");
        getContentPane().add(lblChances);
        lblChances.setBounds(1010, 550, 180, 60);

        jLabel3.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QUESTÃO 10");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 550, 280, 60);

        lblPontos.setFont(new java.awt.Font("Poetsen One", 0, 36)); // NOI18N
        lblPontos.setForeground(new java.awt.Color(255, 255, 255));
        lblPontos.setText("100");
        getContentPane().add(lblPontos);
        lblPontos.setBounds(710, 560, 100, 40);

        lblTemChance11.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        lblTemChance11.setForeground(new java.awt.Color(204, 0, 51));
        lblTemChance11.setText("3");
        getContentPane().add(lblTemChance11);
        lblTemChance11.setBounds(1170, 550, 50, 60);

        jLabel2.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 102));
        jLabel2.setText("/");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1200, 550, 40, 60);

        lblTotChance11.setFont(new java.awt.Font("Poetsen One", 0, 33)); // NOI18N
        lblTotChance11.setForeground(new java.awt.Color(0, 204, 102));
        lblTotChance11.setText("3");
        getContentPane().add(lblTotChance11);
        lblTotChance11.setBounds(1220, 550, 50, 60);

        lblCabecalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lblCabecalho.png"))); // NOI18N
        lblCabecalho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(lblCabecalho);
        lblCabecalho.setBounds(-10, 530, 1400, 100);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("Escolher o Próximo Nível");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 290, 480, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("Clique no Botão voltar Para");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 210, 520, 50);

        lblNivel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblNivel.setText("O Nível  Fácil");
        getContentPane().add(lblNivel);
        lblNivel.setBounds(410, 140, 290, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Parabéns Você Completou ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 70, 520, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/zmsgFinal.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1362, 530);

        setBounds(0, -27, 1354, 660);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:       
        //play("/audio/Aplausos");
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblChances;
    public javax.swing.JLabel lblNivel;
    public javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lblPotuacao;
    public javax.swing.JLabel lblTemChance11;
    public javax.swing.JLabel lblTotChance11;
    // End of variables declaration//GEN-END:variables
}
